{"uuid": "e517a82f-fb8a-40e1-b1fa-d79a11259db4", "children": ["74102f0e-841d-4078-910d-ff20a05552ec"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: MicrosoftEdge=137.0.3296.93)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff7fd573985+25605]\n\t(No symbol) [0x0x7ff7fd4c3a90]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x0x7ff7fd7f6fca+1962554]\n\t(No symbol) [0x0x7ff7fd289110]\n\t(No symbol) [0x0x7ff7fd27d3af]\n\t(No symbol) [0x0x7ff7fd27ea26]\n\t(No symbol) [0x0x7ff7fd27d619]\n\t(No symbol) [0x0x7ff7fd27d21c]\n\t(No symbol) [0x0x7ff7fd27cf68]\n\t(No symbol) [0x0x7ff7fd27af5b]\n\t(No symbol) [0x0x7ff7fd27b53c]\n\t(No symbol) [0x0x7ff7fd28f6ba]\n\t(No symbol) [0x0x7ff7fd317b6e]\n\t(No symbol) [0x0x7ff7fd2f9e4a]\n\t(No symbol) [0x0x7ff7fd2cea5d]\n\t(No symbol) [0x0x7ff7fd3175df]\n\t(No symbol) [0x0x7ff7fd2f9bb3]\n\t(No symbol) [0x0x7ff7fd2cdf56]\n\t(No symbol) [0x0x7ff7fd2cd463]\n\t(No symbol) [0x0x7ff7fd2cdd83]\n\t(No symbol) [0x0x7ff7fd3ce0fd]\n\t(No symbol) [0x0x7ff7fd3ddd08]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x0x7ff7fd658959+265161]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x0x7ff7fd660261+296145]\n\t(No symbol) [0x0x7ff7fd4d2231]\n\t(No symbol) [0x0x7ff7fd4ca6d4]\n\t(No symbol) [0x0x7ff7fd4ca823]\n\t(No symbol) [0x0x7ff7fd4bb9f6]\n\tBaseThreadInitThunk [0x0x7ffc0551e8d7+23]\n\tRtlUserThreadStart [0x0x7ffc06d9c34c+44]\n\n", "trace": "  File \"C:\\Users\\varun\\PycharmProjects\\PytestAutomation\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\varun\\PycharmProjects\\PytestAutomation\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\varun\\PycharmProjects\\PytestAutomation\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\varun\\PycharmProjects\\PytestAutomation\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\varun\\PycharmProjects\\PytestAutomation\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\varun\\PycharmProjects\\ecommercesite\\tests\\conftest.py\", line 19, in setup\n    driver.get(url)\n  File \"C:\\Users\\varun\\PycharmProjects\\PytestAutomation\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\varun\\PycharmProjects\\PytestAutomation\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\varun\\PycharmProjects\\PytestAutomation\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750826592053, "stop": 1750826595863}], "start": 1750826592053, "stop": 1750826595921}